### PR TITLE
caching nvm and npm modules

### PR DESCRIPTION
**Pull request by udnisap**

### CODE REVIEW

**Comment by iamstarkov** [comment]
Hey @udnisap, why do you need this?

**Comment by SBoudrias** [comment]
This could actually cause a bunch of new issues.

**Comment by SBoudrias** [comment]
Here's some background on the question https://github.com/yeoman/generator-node/issues/154

**Comment by iamstarkov** [comment]
yep, and as far as [original problem](https://github.com/yeoman/generator-generator/pull/134) was not cache related, I feel like closing pull-request. @udnisap if you think we still need this changes, please write your thougths

**Comment by udnisap** [comment]
:+1:

**Pull request closed without merging**
