### PR TITLE
Update to yeoman-generator 2.0

### PR DESCRIPTION
**Pull request by SBoudrias**
Should work as is :)

We'd like to get this merge and release as an old version of `debug` is causing `nsp` to fail on generator-node.

Thanks!!

### CODE REVIEW

**Comment by SBoudrias** [comment]
My bad, I was on the wrong head. I think we just need to release the latest master branch.

**Comment by iamstarkov** [comment]
oh, semantic-release broke backwards compatibility. perfect

**Comment by iamstarkov** [comment]
@SBoudrias i added you as a collaborator on npm https://www.npmjs.com/package/generator-travis/access

**Comment by iamstarkov** [comment]
i'll fix the semantic-release stuff in the meantime

**Comment by iamstarkov** [comment]
i tried, semrel won. i'll release it manually

**Comment by iamstarkov** [comment]
@SBoudrias here we go

```
+ generator-travis@1.5.4
```

**Pull request closed without merging**
